spring:
  servlet:
    multipart:
      #设置单个文件上传大小
      max-file-size: 10MB
      #设置总上传的数据大小
      max-request-size: 50MB
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booksys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Cyt1694458081


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cyt.library.bean
server:
  port: 8080
